/**
 * Sistema de Resúmenes Locales sin IA
 * Basado en TF-IDF + Vectores Semánticos (100 dimensiones)
 * Optimizado para Intel i5 2da generación sin GPU dedicada
 * 
 * Maneja:
 * - Vocabulario médico y bioquímico
 * - Traducción inglés → español
 * - Modos Rápido/Preciso
 * - Historial FIFO de 3 resúmenes
 * - Exportación a Google Docs
 */

const LOCAL_SUMMARY_VERSION = '1.1.0';

// ==========================================
// CONFIGURACIÓN GLOBAL
// ==========================================
const SUMMARY_CONFIG = {
    maxHistoryItems: 3,
    maxProcessingTime: {
        FAST: 120,   // 2 minutos
        PRECISE: 300 // 5 minutos
    },
    vectorDimensions: 100,
    maxSentences: {
        FAST: 15,
        PRECISE: 25
    },
    weights: {
        FAST: { tfidf: 0.8, vector: 0.2 },
        PRECISE: { tfidf: 0.5, vector: 0.5 }
    }
};

// ==========================================
// DICCIONARIO MÉDICO ESPECIALIZADO
// ==========================================
const MEDICAL_DICTIONARY = {
    synonyms: {
        'cardíaco': ['cardiovascular', 'cardiológico', 'del corazón'],
        'presión': ['tensión arterial', 'hipertensión', 'tensión'],
        'azúcar': ['glucosa', 'carbohidrato', 'endulzante'],
        'corazón': ['miocardio', 'órgano cardíaco', 'ventrículo'],
        'sangre': ['plasma', 'sangre arterial', 'sangre venosa'],
        'cerebro': ['encéfalo', 'cerebral', 'sistema nervioso central'],
        'hígado': ['hepático', 'órgano hepático', 'parénquima hepático'],
        'riñón': ['renal', 'nefronas', 'sistema renal'],
        'glucosa': ['azúcar en sangre', 'glucemia', 'dextrosa'],
        'insulina': ['hormona pancreática', 'hormona glucémica'],
        'colesterol': ['lípidos', 'grasas sanguíneas', 'perfil lipídico'],
        'presión arterial': ['tensión arterial', 'TA', 'PA'],
        'frecuencia cardíaca': ['pulso', 'FC', 'latidos por minuto'],
        'respiración': ['ventilación', 'frecuencia respiratoria', 'FR'],
        'temperatura': ['fiebre', 'hipotermia', 'temperatura corporal'],
        'oxígeno': ['saturación de oxígeno', 'SpO2', 'oxigenación'],
        'diabetes': ['diabetes mellitus', 'DM', 'glucemia alterada'],
        'hipertensión': ['HTA', 'presión alta', 'hipertenso'],
        'infarto': ['infarto de miocardio', 'ataque cardíaco', 'IAM'],
        'ictus': ['accidente cerebrovascular', 'ACV', 'derrame cerebral'],
        'cáncer': ['neoplasia', 'tumor', 'carcinoma']
    },

    translations: {
        'heart': 'corazón',
        'blood': 'sangre',
        'pressure': 'presión',
        'diabetes': 'diabetes',
        'cancer': 'cáncer',
        'brain': 'cerebro',
        'liver': 'hígado',
        'kidney': 'riñón',
        'glucose': 'glucosa',
        'insulin': 'insulina',
        'cholesterol': 'colesterol',
        'blood pressure': 'presión arterial',
        'heart rate': 'frecuencia cardíaca',
        'respiration': 'respiración',
        'temperature': 'temperatura',
        'oxygen': 'oxígeno',
        'hypertension': 'hipertensión',
        'infarction': 'infarto',
        'stroke': 'ictus',
        'tumor': 'tumor',
        'enzyme': 'enzima',
        'protein': 'proteína',
        'DNA': 'ADN',
        'RNA': 'ARN',
        'metabolism': 'metabolismo',
        'hormone': 'hormona',
        'cell': 'célula',
        'tissue': 'tejido',
        'organ': 'órgano',
        'system': 'sistema',
        'disease': 'enfermedad',
        'treatment': 'tratamiento',
        'diagnosis': 'diagnóstico',
        'symptom': 'síntoma',
        'sign': 'signo',
        'patient': 'paciente',
        'clinical': 'clínico',
        'laboratory': 'laboratorio',
        'analysis': 'análisis',
        'result': 'resultado',
        'value': 'valor',
        'normal': 'normal',
        'abnormal': 'anormal',
        'high': 'alto',
        'low': 'bajo',
        'increase': 'aumento',
        'decrease': 'disminución',
        'level': 'nivel',
        'concentration': 'concentración',
        'dose': 'dosis',
        'drug': 'medicamento',
        'medication': 'medicación',
        'therapy': 'terapia',
        'surgery': 'cirugía',
        'prognosis': 'pronóstico',
        'recovery': 'recuperación',
        'acute': 'agudo',
        'chronic': 'crónico',
        'benign': 'benigno',
        'malignant': 'maligno',
        'primary': 'primario',
        'secondary': 'secundario',
        'complication': 'complicación',
        'risk': 'riesgo',
        'factor': 'factor',
        'prevention': 'prevención',
        'screening': 'tamizaje',
        'test': 'prueba',
        'exam': 'examen',
        'imaging': 'imágenes',
        'ultrasound': 'ecografía',
        'CT': 'tomografía computada',
        'MRI': 'resonancia magnética',
        'X-ray': 'radiografía',
        'ECG': 'electrocardiograma',
        'EEG': 'electroencefalograma',
        'blood test': 'análisis de sangre',
        'urine test': 'análisis de orina',
        'biopsy': 'biopsia',
        'culture': 'cultivo',
        'antibiotic': 'antibiótico',
        'antiviral': 'antiviral',
        'anti-inflammatory': 'antiinflamatorio',
        'analgesic': 'analgésico',
        'vaccine': 'vacuna',
        'immunization': 'inmunización',
        'infection': 'infección',
        'virus': 'virus',
        'bacteria': 'bacteria',
        'fungus': 'hongo',
        'parasite': 'parásito',
        'immune': 'inmune',
        'antibody': 'anticuerpo',
        'antigen': 'antígeno',
        'allergy': 'alergia',
        'inflammation': 'inflamación',
        'edema': 'edema',
        'pain': 'dolor',
        'fever': 'fiebre',
        'cough': 'tos',
        'dyspnea': 'disnea',
        'fatigue': 'fatiga',
        'weakness': 'debilidad',
        'nausea': 'náuseas',
        'vomiting': 'vómitos',
        'diarrhea': 'diarrea',
        'constipation': 'estreñimiento',
        'headache': 'dolor de cabeza',
        'dizziness': 'mareo',
        'confusion': 'confusión',
        'seizure': 'convulsión',
        'coma': 'coma',
        'shock': 'shock',
        'hypotension': 'hipotensión',
        'hypertension': 'hipertensión',
        'tachycardia': 'taquicardia',
        'bradycardia': 'bradicardia',
        'arrhythmia': 'arritmia',
        'heart failure': 'insuficiencia cardíaca',
        'myocardial infarction': 'infarto de miocardio',
        'angina': 'angina de pecho',
        'atherosclerosis': 'aterosclerosis',
        'stroke': 'ictus',
        'transient ischemic attack': 'ataque isquémico transitorio',
        'dementia': 'demencia',
        'alzheimer': 'alzheimer',
        'parkinson': 'parkinson',
        'epilepsy': 'epilepsia',
        'migraine': 'migraña',
        'asthma': 'asma',
        'COPD': 'EPOC',
        'pneumonia': 'neumonía',
        'bronchitis': 'bronquitis',
        'tuberculosis': 'tuberculosis',
        'peptic ulcer': 'úlcera péptica',
        'gastritis': 'gastritis',
        'hepatitis': 'hepatitis',
        'cirrhosis': 'cirrosis',
        'pancreatitis': 'pancreatitis',
        'cholecystitis': 'colecistitis',
        'nephritis': 'nefritis',
        'renal failure': 'insuficiencia renal',
        'urinary tract infection': 'infección urinaria',
        'arthritis': 'artritis',
        'osteoarthritis': 'osteoartritis',
        'rheumatoid arthritis': 'artritis reumatoide',
        'gout': 'gota',
        'osteoporosis': 'osteoporosis',
        'diabetes mellitus': 'diabetes mellitus',
        'thyroid': 'tiroides',
        'hyperthyroidism': 'hipertiroidismo',
        'hypothyroidism': 'hipotiroidismo',
        'anemia': 'anemia',
        'leukemia': 'leucemia',
        'lymphoma': 'linfoma',
        'HIV': 'VIH',
        'AIDS': 'SIDA',
        'pregnancy': 'embarazo',
        'delivery': 'parto',
        'birth': 'nacimiento',
        'child': 'niño',
        'adult': 'adulto',
        'elderly': 'anciano',
        'male': 'masculino',
        'female': 'femenino',
        'age': 'edad',
        'weight': 'peso',
        'height': 'altura',
        'BMI': 'IMC',
        'body mass index': 'índice de masa corporal'
    }
};

// ==========================================